### ISSUE TITLE
如果功能还能增强一点就好了

### ISSUE THREAD

**Issue by BobJackson** [Jian0326/timestamp#2]
<img width="648" alt="image" src="https://github.com/Jian0326/timestamp/assets/15266708/841af89b-0321-42e8-990e-a86891d2e20c">

1.最核心的是下面的，支持毫秒时间戳（默认可以是秒）；
2.还有就是时间格式，如果能支持多种格式就好了，比如2024-01，也可以转成合法的时间戳（年月也是常用的）。
本来是Pull requests。就当issues提了，意思表达了哈

**Comment by Jian0326** [comment]
1.0.1版本
如果数字长度13按照毫秒计算
新增支持输入2021-04，2024-04-02
